### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by iminders** [iminders/bazel#1]
# Environment
MacOS 10.15.3
Docker Desktop community Version 2.0.0.3 

# How to reproduce
```
docker run -it registry.cn-hangzhou.aliyuncs.com/aiminders/bazel:latest bash

pip install tenvs -i https://pypi.org/simple
```

# Error message
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 279, in run
    session = self.get_default_session(options)
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 74, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 91, in _build_session
    index_urls=self._get_index_urls(options),
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_internal/network/session.py", line 241, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/distro.py", line 122, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/distro.py", line 677, in linux_distribution
    self.version(),
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/distro.py", line 737, in version
    self.lsb_release_attr('release'),
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/distro.py", line 899, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/distro.py", line 552, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/distro.py", line 1012, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.

```

**Comment by iminders** [comment]
Related issue:  https://github.com/pypa/pip/issues/4924

**Comment by iminders** [comment]
solve it by:
```
mv /usr/bin/lsb_release /usr/bin/lsb_release.bak
```
